### ISSUE TITLE
Is it possible to extract this for usage outside vscode?

### ISSUE THREAD

**Issue by MikaelElkiaer** [joelspadin/zmk-tools#1]
Hi, nicely done on the vscode extension, works like a charm.

However, I typically use neovim and would like a similar extension to tree-sitter.
Is it at all possible to extract the grammar here and put into the grammar.js format and then use `tree-sitter generate`?

**Comment by joelspadin** [comment]
The grammar comes from https://github.com/joelspadin/tree-sitter-devicetree. Most of this extension's features are built on top of that though, so just pulling the grammar out won't get you those.

The extension could be restructured to use the language server protocol, but that's a lot of work.

**Comment by MikaelElkiaer** [comment]
Dang, thanks for clarifying though.
